development:
  adapter: postgresql
  database: signup_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: signup_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: signup_production
  pool: 5
  timeout: 5000